# Import Modules

In [1]:
import pandas as pd

# Process the data

## 22. Statlog Heart Disease

In [2]:
df_statlog: pd.DataFrame = pd.read_csv('data/22-statlog.csv')
df_statlog.head()

,age,sex,chest-pain,rest-bp,serum-chol,fasting-blood-sugar,electrocardiographic,max-heart-rate,angina,oldpeak,slope,major-vessels,thal,heart-disease
0,70.0,1.0,4.0,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,3.0,2
1,67.0,0.0,3.0,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,7.0,1
2,57.0,1.0,2.0,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,7.0,2
3,64.0,1.0,4.0,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,7.0,1
4,74.0,0.0,2.0,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,3.0,1

In [3]:
df_statlog.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   270 non-null    float64
 1   sex                   270 non-null    float64
 2   chest-pain            270 non-null    float64
 3   rest-bp               270 non-null    float64
 4   serum-chol            270 non-null    float64
 5   fasting-blood-sugar   270 non-null    float64
 6   electrocardiographic  270 non-null    float64
 7   max-heart-rate        270 non-null    float64
 8   angina                270 non-null    float64
 9   oldpeak               270 non-null    float64
 10  slope                 270 non-null    float64
 11  major-vessels         270 non-null    float64
 12  thal                  270 non-null    float64
 13  heart-disease         270 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 29.7 KB

In [4]:

def preprocess_statlog(df: pd.DataFrame) -> pd.DataFrame:
    df_new = df.copy()
    
    # Rename columns
    df_new.rename(columns={
        "chest-pain": "cp_type",
        "rest-bp": "sbp",
        "serum-chol": "chol",
        "fasting-blood-sugar": "fbs",
        "electrocardiographic": "ecg",
        'max-heart-rate': 'mhr',
        "major-vessels": "mv",
        "heart-disease": "target"
    }, inplace=True)
    
    # Change thal values: 3 -> 0 (normal), 6 -> 1 (fixed), 7 -> 2 (reversible)
    df_new['thal'] = df_new['thal'].map({3: 0, 6: 1, 7: 2})
    
    # Change target values: 1 -> 0 (absent), 2 -> 1 (present)
    df_new['target'] = df_new['target'].map({1: 0, 2: 1})
    
    # Change datatypes
    df_new = df_new.astype({
        'age': 'int64',
        'sex': 'int64',
        'cp_type': 'int64',
    })
    
    return df_new

In [5]:
df_preprocessed_statlog = preprocess_statlog(df_statlog)
df_preprocessed_statlog.head()

,age,sex,cp_type,sbp,chol,fbs,ecg,mhr,angina,oldpeak,slope,mv,thal,target
0,70,1,4,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,0,1
1,67,0,3,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,2,0
2,57,1,2,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,2,1
3,64,1,4,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,2,0
4,74,0,2,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,0,0

## 23. Coronary Heart Disease

In [6]:
df_chd = pd.read_csv('data/23-chd.csv')
df_chd.head()

   sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
0  160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
1  144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
2  118     0.08  3.48      32.28  Present     52    29.14     3.81   46    0
3  170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
4  134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1

## 24. Framingham

In [7]:
df_framingham = pd.read_csv('data/24-framingham.csv')
df_framingham.head()

,Sex,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,male,39,4.0,No,0.0,0.0,0,0,No,195.0,106.0,70.0,26.97,80.0,77.0,0
1,female,46,2.0,No,0.0,0.0,0,0,No,250.0,121.0,81.0,28.73,95.0,76.0,0
2,male,48,1.0,Yes,20.0,0.0,0,0,No,245.0,127.5,80.0,25.34,75.0,70.0,0
3,female,61,3.0,Yes,30.0,0.0,0,1,No,225.0,150.0,95.0,28.58,65.0,103.0,1
4,female,46,3.0,Yes,23.0,0.0,0,0,No,285.0,130.0,84.0,23.10,85.0,85.0,0

## 25. Heart Disease

In [8]:
df_heart = pd.read_csv('data/25-heart.csv')
df_heart.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [9]:
df_heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [10]:

def preprocess_heart(df: pd.DataFrame) -> pd.DataFrame:
    df_new = df.copy()
    
    # Rename columns
    df_new.rename(columns={
        "cp": "cp_type",
        "trestbps": "sbp",
        "restecg": "ecg",
        "thalach": "hr",
        "exang": "angina",
        "ca": "mv"
    }, inplace=True)
    
    # Change cp_type values: 0 -> 1 (typical angina), 1 -> 2 (atypical angina), 2 -> 3 (non-anginal pain), 3 -> 4 (asymptomatic)
    df_new['cp_type'] = df_new['cp_type'].map({0: 1, 1: 2, 2: 3, 3: 4})
    
    return df_new

In [11]:
df_preprocessed_heart = preprocess_heart(df_heart)
df_preprocessed_heart.head()

,age,sex,cp_type,sbp,chol,fbs,ecg,hr,angina,oldpeak,slope,mv,thal,target
0,52,1,1,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,1,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,1,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,1,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,1,138,294,1,1,106,0,1.9,1,3,2,0

## 26. Stroke

In [13]:
df_stroke = pd.read_csv('data/26-stroke.csv')
df_stroke.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1